# Generated by Django 4.1.1 on 2022-09-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_estoque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='necessario',
            field=models.IntegerField(default=1),
        ),
    ]
